const canvas=document.querySelector('#gameCanvas');const ctx=canvas.getContext('2d');const startBtn=document.querySelector('#startBtn');const scoreEl=document.querySelector('#score');const bestEl=document.querySelector('#highScore');const lastEl=document.querySelector('#lastScore');const message=document.querySelector('#message');const title=document.querySelector('#messageTitle');const text=document.querySelector('#messageText');
const W=canvas.width,H=canvas.height,bird={x:145,y:280,r:18};const gravity=.58,lift=-10,speed=3.3,gap=175,pipeWidth=78;let velocity=0,pipes=[],score=0,running=false,frame=0,raf=0;let best=Number(localStorage.getItem('flappyHighScore')||0),last=Number(localStorage.getItem('flappyLastScore')||0);lastEl.textContent=last;bestEl.textContent=best;
function hud(){scoreEl.textContent=score;bestEl.textContent=best;lastEl.textContent=last}function show(t,m){title.textContent=t;text.textContent=m;message.classList.remove('hidden')}function hide(){message.classList.add('hidden')}
function start(){cancelAnimationFrame(raf);bird.y=H/2;velocity=0;pipes=[];score=0;frame=0;running=true;hide();startBtn.textContent='Restart Game';hud();loop()}function flap(){if(!running){start();return}velocity=lift}
function loop(){if(!running)return;velocity+=gravity;bird.y+=velocity;if(frame%105===0){const top=70+Math.random()*(H-gap-170);pipes.push({x:W+10,top,scored:false})}draw();for(const p of pipes){p.x-=speed;if(!p.scored&&p.x+pipeWidth<bird.x){p.scored=true;score++;hud()}if(hit(p)){end();return}}pipes=pipes.filter(p=>p.x+pipeWidth>0);if(bird.y-bird.r<=0||bird.y+bird.r>=H){end();return}frame++;raf=requestAnimationFrame(loop)}
function hit(p){const nearestX=Math.max(p.x,Math.min(bird.x,p.x+pipeWidth));const nearestY=bird.y;const horizontal=bird.x+bird.r>p.x&&bird.x-bird.r<p.x+pipeWidth;return horizontal&&(bird.y-bird.r<p.top||bird.y+bird.r>p.top+gap)}
function draw(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#202d67');g.addColorStop(1,'#55bdc7');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(255,255,255,.4)';for(let i=0;i<35;i++){const x=(i*97+frame*.15)%W,y=(i*53)%H;ctx.fillRect(x,y,2,2)}for(const p of pipes){ctx.fillStyle='#66b95e';ctx.fillRect(p.x,0,pipeWidth,p.top);ctx.fillRect(p.x-7,p.top-20,pipeWidth+14,20);ctx.fillRect(p.x,p.top+gap,pipeWidth,H);ctx.fillRect(p.x-7,p.top+gap,pipeWidth+14,20)}ctx.save();ctx.translate(bird.x,bird.y);ctx.rotate(Math.max(-.5,Math.min(.8,velocity/12)));ctx.font='38px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('🐦',0,0);ctx.restore()}
function end(){running=false;cancelAnimationFrame(raf);last=score;localStorage.setItem('flappyLastScore',String(last));if(score>best){best=score;localStorage.setItem('flappyHighScore',String(best));show('NEW BEST!',`Score ${score} • Best ${best}`)}else show('GAME OVER',`Score ${score} • Best ${best}`);hud()}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();flap()});startBtn.addEventListener('click',start);document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();flap()}});show('READY?','Press Start or Space to begin');hud();
